#!/bin/bash

# Enable the proxy extension in notebook and lab
jupyter labextension install --clean @jupyter-widgets/jupyterlab-manager \
                                     @jupyterlab/server-proxy

#code-server --install-extension ms-python.python
